### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by sjmadsen** [chargebee/chargebee-ios#17]
While CocoaPods is still very popular, Swift Package Manager is Apple's official mechanism to add dependencies to an app. Please consider adding a `Package.swift` manifest to directly support SPM.

**Comment by JeevenMann** [comment]
Bump, 2022 still no support

**Comment by cb-saisrikant** [comment]
Support for Swift Package Manager is added in v1.0.3. Please use this version.
