### ISSUE TITLE
iOS IAP validation failing with Authentication Failed

### ISSUE THREAD

**Issue by Titaye** [chargebee/chargebee-ios#28]
I'm not able to validate an In App purchase. 
When calling the `purchaseProduct` method, I get an authentication failed error when the sdk is calling the chargebee server side validation endpoint.
I'm able to get my products from the SDK so I think my keys are valid. And I doubled checked the sdk key.
I'm testing with a sandbox user, Is there something special to configure in order to make it working ?

Thanks

**Comment by cb-saisrikant** [comment]
Please make sure that all prerequisites are configured in Chargebee for SDK to work. Refer to following link to know about prerequisites configuration: [Prerequisites configuration for App store integration](https://www.chargebee.com/docs/2.0/mobile-app-store-product-iap.html)
Here's the [link](https://drive.google.com/file/d/1YlPqZAzNvAPLuGYV35EFMIC4OiPgVMgM/view) to demo video that will help you to understand this better. 
We can get into call if you want to understand this better. Please let us know.

**Comment by cb-saisrikant** [comment]
Hi, We have released a latest version of SDK and update the prerequisites link as well in the readme file. Hope you were able to have a look at the video and setup the application at your end. Please let us know if you need any help on this. Thanks

**Comment by Titaye** [comment]
HI, Thanks my authentication error is gone but I am now facing an error message from your SDK at the end of the purchase.
My subscription id is not found.

Thanks

**Comment by Titaye** [comment]
Ok the plan was not created for all the currencies available. Using EUR when only USD is declared will lead to a subscription purchased from apple but not on chargebee

**Comment by cb-saisrikant** [comment]
Please confirm if all the currencies (including EUR) were configured in Chargebee. If all the currencies are configured then plan & subscription creation will happen.
