### ISSUE TITLE
Update user info

### ISSUE THREAD

**Issue by tbates-up** [chargebee/chargebee-ios#38]
Hi, is there a way to update a user's data such as email, first and last name?

When making a purchase, it appears to create a new customer in the dashboard, but I am unable to populate that user with more information.

**Comment by cb-saisrikant** [comment]
Hi, SDK takes only customer id as input. The purpose is to link customer id to subscription object.
If you want to update the details such as email, first and last name then please use Chargebee's REST APIs to update the customer object.

**Comment by cb-haripriyan** [comment]
Hi @tbates-up https://github.com/chargebee/chargebee-ios#buy-or-subscribe-product should address this.
