### ISSUE TITLE
Failure callback not being called in purchaseNonSubscriptionProduct

### ISSUE THREAD

**Issue by msschwartz** [chargebee/chargebee-ios#67]
The completion callback is never called when in-app purchase fails when making non-subscription purchase.

In the CBPurchaseManager it looks like the payment queue observer is calling `buyProductHandler` rather than `buyNonSubscriptionProductHandler` in the transaction failure block.

```
CBPurchase.shared.purchaseNonSubscriptionProduct(product: product, customer: customer, productType: productType) { result in
  switch result {
  ...
  case .failure():
    // This is never called
  }
}
```

**Comment by cb-haripriyan** [comment]
Thanks @msschwartz 
This should be fixed with the release [1.0.22](https://github.com/chargebee/chargebee-ios/releases/tag/1.0.22)
Can you please check it and let us know?
cc: @cb-gadagoju
